#ifndef TOGOSARDUINOAPPS2021_PREPROCFUN_H
#define TOGOSARDUINOAPPS2021_PREPROCFUN_H
#define TOGOSARDUINOAPPS2021_NAMEOF__2(WHAT) #WHAT
// TOGOSARDUINOAPPS2021_NAMEOF(foo) -> "foo"
#define TOGOSARDUINOAPPS2021_NAMEOF(WHAT) TOGOSARDUINOAPPS2021_NAMEOF__2(WHAT)
// TOGOSARDUINOAPPS2021_CONFIG_HASH_TO_INCLUDESPEC(hithere,abc123) -> "hithere-abc123.h"
#define TOGOSARDUINOAPPS2021_CONFIG_HASH_TO_INCLUDESPEC(PREFIX,HASH) TOGOSARDUINOAPPS2021_NAMEOF(PREFIX-HASH.h)
#endif
