** [2021-06-25] Frustration

Trying to get an SSD1306 display to work
with my WeMos D1 Mini.
Also there is sometimes an SHT20 connected to the same I2C bus.

Maybe this OLED display doesn't have a built-in pull-up resistor?
Because it seems to work only when I also have the SHT20 plugged into the I2C bus.
Otherwise no examples were working.

Address = 0x3C seems to be right, though it is a 128x64, not a 128x32.
Before I left Madison it seemed I got PowerCube 1ce50d00 working, but *not* the Adafruit library.

But as of [2021-06-25T01:09:40-05:00] it's the other way around.

Not only does PowerCube (and also the ACROBOTIC_SSD1306 example) not display anything; it crashes!
I think this is actually due to the font memory not being handled correctly.
Maybe if I change it to just be a regular uint8_t[]...

[2021-06-25T01:24:23-05:00] Yep.  Commenting out this stuff did the job:

#+BEGIN_SRC c++
#elif defined(ESP8266)
  #include <pgmspace.h>
  #define OLEDFONT(name) static const uint8_t name[]
#+END_SRC

Okay, time to copy over that newer (fad6a0f85fc4b241a14282e2da580b258256cf0a) PowerCube stuff
and make some new alterations.

Alright, it all seems working now.
Remember!
- That PROGMEM font stuff can be problematic; could be there was a mismatch
  between the declaration and access; look into it later.
- This particular SSD1306 (all B&W - this one doesn't have that nice yellow strip)
  seems to work only when the SHT20 is also plugged in.

[2021-06-25T02:20] I unplugged the SHT20 and rebooted the thing and it seems still working.
Maybe it's just the SHT20 has to be plugged in when you first program it, idfk.

[2021-06-25T02:24] Hmm; that doesn't seem to be the case, either.
Maybe the SHT20 needing to be plugged in was a red herring.


** [2021-06-25]

Somewhat mystified about why, after I've written a new program to my WeMos board
that doesn't do anything with the SSD1306, body text is still scrolling.
Did I tell it to automatically scroll?  Must have.  Humph.

I suppose I should document those commands in SomeText.ino's ~loop~.

** [2025-07-13]

Added ~gotoRowCol~ to Printer so you don't need to reference the driver directly.
