#+TITLE: TOGoS's Arduino Apps

Actually ESP8266 apps, mostly for WeMos D1 mini,
but I use the Arduino framework and IDE.

These rely on TOGoSArduinoLibs2021, which will hopefully
help me share code better than the other scattered Arduino projects.
I thought of making this just an 'apps' branch in that
same repo (which would also include the libs),
but I can always merge them later.

*** "Old" arduino projects

For reference.
Or maybe to update them to the new conventions and import them.

"Old" meaning "before TOGoSArduinoLibs20201"

- ArduinoPowerSwitch
- ESP8266-MQTT-Sensor
- Thermostat2019
- PowerCube
- ArduinoLightController
- ArduinoLEDAnimator2021
- ArduinoChargeController

** Cross-app standards

Secrets can be stored, not checked into the Git repo, in ~secrets-GITOBJECTHASH.h~ files,
and referenced by ~config.h~ files, which are checked in on 'instance' branches.

This way the exact configuration, including a hash of the secrets file,
can be reported by the app without exposing the contents of the secrets.

*** Standard secret constants

To indicate hardcoded WiFi networks that should be periodically auto-[re]connected-to:

#+begin_src
#define TOGOSARDUINOAPPS2021_WIFINET0_SSID "MyNetworkSSID"
#define TOGOSARDUINOAPPS2021_WIFINET0_PASSWORD "My network passowrd goes here."
#+end_src

More than one WiFi network can be listed, by incrementing the number in each one.
Apps may or may not look at them all.
(I may declare an expected number of supported networks later.)
