name=TOGoS Preprocessor Fun
version=0.0.1
author=TOGoS
maintainer=TOGoS
sentence=Header files of macro stuff that you wouldn't be blamed for not wanting to touch with a 10-foot pole.
paragraph=
url=http://github.com/TOGoS/TOGoSArduinoLibs2021/
