// Helpers for your config.h

#ifndef PREPROCFUN_H
#define PREPROCFUN_H
#define ES2021_STRINGIFY__2(WHAT) #WHAT
#define ES2021_STRINGIFY(WHAT) ES2021_STRINGIFY__2(WHAT)
#define ES2021_CONFIG_HASH_TO_INCLUDESPEC(HASH) ES2021_STRINGIFY(config-HASH.h)
#endif
